apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cheap-wildfowl-python
  janus-idp.io/tekton: cheap-wildfowl-python
  backstage.io/kubernetes-id: cheap-wildfowl-python
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: cheap-wildfowl-python
resources: 
- deployment.yaml
- route.yaml
- service.yaml
