apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cheap-wildfowl-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cheap-wildfowl-python 
  name: cheap-wildfowl-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: cheap-wildfowl-python 
